---
dependencies: []

galaxy_info:
  role_name: ansible_role_puppet_agent
  author: habbis
  description: setu puppet agen on most Unix-like systems.
  company: "nocompany"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - system
